version: '2'
services:
  app:
    build: .
    container_name: 'client'
    ports:
      - '80:8080'
    links:
      - fluentd
    environment:
      TZ: 'Asia/Tokyo'

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/tmp/logs
    ports:
      - '24224:24224'
